name: Auto Assign Issues
on:
  issues:
    types: [opened]

permissions:
  issues: write # Grant write permission to issues

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue opener is org member
        id: is_org_member
        uses: JamesSingleton/is-organization-member@1.1.0
        with:
          organization: splunk
          username: ${{ github.event.issue.user.login }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add label "external"
        if: steps.is_org_member.outputs.result == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: external
        run: gh issue edit "$NUMBER" --add-label "$LABELS"

      - uses: pozil/auto-assign-issue@v2
        if: steps.is_org_member.outputs.result == 'false'
        with:
          assignees: lingy1028,ahoang-splunk,ifonsecam
          numOfAssignee: 1
          allowSelfAssign: false
